[theme]

# Primary accent for interactive elements
primaryColor = "#540B0E"

# Background color for the main content area
backgroundColor = "#F5F6F4"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#C27070"

# Color used for almost all text
textColor = "#1E000E"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"